/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domogui;

import fnArchivo.archivo;
import dispositivos.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class Dashboard extends javax.swing.JFrame {
    ConexionSerial con;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() throws Exception {
        initComponents();
        
        //configurando imagen en etiqueta
        try{
            BufferedImage casaPlano = ImageIO.read(new File("imgDashB/houseplan2.jpg"));
            lbcasa2.setIcon(new ImageIcon(casaPlano));
            
            BufferedImage ardlogo = ImageIO.read(new File("imgDashB/arduinologo2.png"));
            iconArduino.setIcon(new ImageIcon(ardlogo));
            
            BufferedImage refresh = ImageIO.read(new File("imgDashB/refresh.png"));
            BufferedImage refreshp = ImageIO.read(new File("imgDashB/refreshp.png"));
            btActualizar.setIcon(new ImageIcon(refresh));
            btActualizar.setPressedIcon(new ImageIcon(refreshp));
            
            BufferedImage close = ImageIO.read(new File("imgDashB/close.png"));
            BufferedImage closep = ImageIO.read(new File("imgDashB/closep.png"));
            btCerrar.setIcon(new ImageIcon(close));
            btCerrar.setPressedIcon(new ImageIcon(closep));
            
            BufferedImage casaT = ImageIO.read(new File("imgDashB/house_icont.png"));
            lbcasaT.setIcon(new ImageIcon(casaT));
            
            BufferedImage temp = ImageIO.read(new File("imgDashB/tempIcon.png"));
            lbtempIcon.setIcon(new ImageIcon(temp));
            
            //LEDs
            lbled1.setIcon(new ImageIcon("img/led_blue1.png"));
            lbled2.setIcon(new ImageIcon("img/led_green1.png"));
            
            
        }catch (Exception e){
            
        }

        //Funciones oara coneccion serial
        con = new ConexionSerial(this);
        actualizarPuertos();
        
        
        //mostrando numero de sensores y actuadores
        ArrayList<Sensor> nsens = archivo.obtener_registroS();
        ArrayList<Actuador> nacts = archivo.obtener_registroA();                
        nDispositivos(nsens,nacts);
        
        //calculo de temperatura de sensores
        tempMediaCasa(nsens);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconArduino = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfnSensores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfnAct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btCerrar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        lbcasaT = new javax.swing.JLabel();
        lbtempIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTemp = new javax.swing.JTextField();
        lbcasa2 = new javax.swing.JLabel();
        lbinfoCasa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfDormitorioSensores = new javax.swing.JTextField();
        tfDormitorioActua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfBanoSensores = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfBanoActua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfSalaSens = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfSalaAct = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfCocinaSens = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfCocinaAct = new javax.swing.JTextField();
        btled1 = new javax.swing.JToggleButton();
        btled2 = new javax.swing.JToggleButton();
        lbled1 = new javax.swing.JLabel();
        lbled2 = new javax.swing.JLabel();
        btconectar = new javax.swing.JButton();
        btdesconectar = new javax.swing.JButton();
        cbPuerto = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DashBoard");

        iconArduino.setName(""); // NOI18N
        iconArduino.setPreferredSize(new java.awt.Dimension(75, 75));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todo", "Sensores", "Actuadores" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de Sensores:");

        tfnSensores.setEditable(false);
        tfnSensores.setMinimumSize(new java.awt.Dimension(50, 27));
        tfnSensores.setPreferredSize(new java.awt.Dimension(50, 27));
        tfnSensores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnSensoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de Actuadores:");

        tfnAct.setEditable(false);
        tfnAct.setMinimumSize(new java.awt.Dimension(50, 27));
        tfnAct.setPreferredSize(new java.awt.Dimension(50, 27));
        tfnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnActActionPerformed(evt);
            }
        });

        jLabel3.setText("Visualizar");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btCerrar.setText("Cerrar");
        btCerrar.setPreferredSize(new java.awt.Dimension(90, 30));
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar Puertos");
        btActualizar.setPreferredSize(new java.awt.Dimension(90, 30));
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        lbcasaT.setPreferredSize(new java.awt.Dimension(128, 128));

        lbtempIcon.setPreferredSize(new java.awt.Dimension(55, 100));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setText("Temp °C");

        tfTemp.setEditable(false);
        tfTemp.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        tfTemp.setText("30");
        tfTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTempActionPerformed(evt);
            }
        });

        lbcasa2.setPreferredSize(new java.awt.Dimension(407, 328));

        lbinfoCasa.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbinfoCasa.setText("Vista Superior Total");

        jLabel5.setText("Dormitorio");

        jLabel6.setText("Baño");

        jLabel7.setText("Sala");

        jLabel8.setText("Cocina/Comedor");

        jLabel9.setText("S:");

        jLabel10.setText("A:");

        tfDormitorioSensores.setEditable(false);
        tfDormitorioSensores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDormitorioSensoresActionPerformed(evt);
            }
        });

        tfDormitorioActua.setEditable(false);

        jLabel11.setText("S:");

        tfBanoSensores.setEditable(false);
        tfBanoSensores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBanoSensoresActionPerformed(evt);
            }
        });

        jLabel12.setText("A:");

        tfBanoActua.setEditable(false);

        jLabel13.setText("S:");

        tfSalaSens.setEditable(false);
        tfSalaSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalaSensActionPerformed(evt);
            }
        });

        jLabel14.setText("A:");

        tfSalaAct.setEditable(false);

        jLabel15.setText("S:");

        tfCocinaSens.setEditable(false);
        tfCocinaSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCocinaSensActionPerformed(evt);
            }
        });

        jLabel16.setText("A:");

        tfCocinaAct.setEditable(false);

        btled1.setText("led1");
        btled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btled1ActionPerformed(evt);
            }
        });

        btled2.setText("led2");
        btled2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btled2ActionPerformed(evt);
            }
        });

        lbled1.setText("  ");
        lbled1.setPreferredSize(new java.awt.Dimension(30, 30));

        lbled2.setText("  ");
        lbled2.setPreferredSize(new java.awt.Dimension(30, 30));

        btconectar.setText("Conectar");
        btconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconectarActionPerformed(evt);
            }
        });

        btdesconectar.setText("Desconectar");
        btdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdesconectarActionPerformed(evt);
            }
        });

        cbPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPuertoActionPerformed(evt);
            }
        });

        jLabel17.setText("Puertos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfnSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnAct, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfDormitorioSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfDormitorioActua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBanoSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBanoActua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbinfoCasa)
                            .addComponent(lbcasa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbcasaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbtempIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btled1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btled2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(iconArduino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbled1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbled2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfSalaSens, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(tfTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(83, 83, 83))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cbPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfSalaAct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(btconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCocinaAct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCocinaSens, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(btdesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tfnSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfnAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbinfoCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcasa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(tfDormitorioSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tfDormitorioActua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(tfBanoSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(tfBanoActua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtempIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcasaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconArduino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tfSalaSens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfSalaAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(tfCocinaSens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(tfCocinaAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btled1)
                                    .addComponent(lbled2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btled2)
                                    .addComponent(lbled1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tfnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnActActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void tfTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTempActionPerformed

    private void tfDormitorioSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDormitorioSensoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDormitorioSensoresActionPerformed

    private void tfBanoSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBanoSensoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBanoSensoresActionPerformed

    private void tfSalaSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalaSensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalaSensActionPerformed

    private void tfCocinaSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCocinaSensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCocinaSensActionPerformed

    private void tfnSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnSensoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnSensoresActionPerformed

    private void btled2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btled2ActionPerformed
        // TODO add your handling code here:
        enviarDatos();
    }//GEN-LAST:event_btled2ActionPerformed

    private void cbPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPuertoActionPerformed
        // TODO add your handling code here:
        if(cbPuerto.getSelectedIndex()>=0)
            btconectar.setEnabled(true);
        else
            btconectar.setEnabled(false);
    }//GEN-LAST:event_cbPuertoActionPerformed

    private void btconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconectarActionPerformed
        // TODO add your handling code here:
        if(con.conectar(cbPuerto.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(this,"Conexion exitosa","Conexion",JOptionPane.INFORMATION_MESSAGE);
            btdesconectar.setEnabled(true);
            btconectar.setEnabled(false);
            cbPuerto.setEnabled(false);
            btActualizar.setEnabled(false);
            btled1.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this,"Ocurrio un error en la conexion o el puerto ya esta siendo utilizado","Conexion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btconectarActionPerformed

    private void btdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdesconectarActionPerformed
        // TODO add your handling code here:
        con.desconectar();
        cbPuerto.setEnabled(true);
        btActualizar.setEnabled(true);
        btconectar.setEnabled(true);
        lbled1.setEnabled(false);
        btdesconectar.setEnabled(false);
    }//GEN-LAST:event_btdesconectarActionPerformed

    private void btled1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btled1ActionPerformed
        // TODO add your handling code here:
                enviarDatos();
    }//GEN-LAST:event_btled1ActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        actualizarPuertos();
    }//GEN-LAST:event_btActualizarActionPerformed

    public void nDispositivos(ArrayList<Sensor> s, ArrayList<Actuador> a){
        int ns=0, na=0, i = 0;
        for(i = 0; i<s.size();i++){
            ns++;
        }
        for (i =0; i<a.size();i++){
            na++;
        }
        tfnAct.setText(String.valueOf(na));
        tfnSensores.setText(String.valueOf(ns));
        
    }
    
    public void tempMediaCasa(ArrayList<Sensor> st){
        int temp, tempTotal=0, n=0;
        String tipo="temp";
        for (int i=0;i<st.size();i++){
            if ((st.get(i).getTipo().equalsIgnoreCase(tipo))){
                n++;
                temp = (int) st.get(i).getValAct();
                tempTotal = tempTotal + temp;
            }
        }
        if (n==0){
            tfTemp.setText("0");
        }else{
            tfTemp.setText(String.valueOf(tempTotal/n));
        }
    }
    
        private void actualizarPuertos(){
        Vector puertos = ConexionSerial.obtenerPuertos();
        cbPuerto.removeAllItems();
        for (int i = 0; i < puertos.size(); i++) 
            cbPuerto.addItem(puertos.get(i));
    }
    
        private void cbPuertoItemStateChanged(java.awt.event.ItemEvent evt) {                                          
        if(cbPuerto.getSelectedIndex()>=0)
            btconectar.setEnabled(true);
        else
            btconectar.setEnabled(false);
    }
        
    public synchronized void actualizarEstadoLEDs(int n){
        if(n==1){           
            try {
                lbled1.setIcon(new ImageIcon("img/led_green2.png"));
                Thread.sleep(1000);                 
                lbled1.setIcon(new ImageIcon("img/led_green1.png"));
            } catch(InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
        }else if(n==2){
            try {
                lbled2.setIcon(new ImageIcon("img/led_blue2.png"));
                Thread.sleep(1000);                 
                lbled2.setIcon(new ImageIcon("img/led_blue1.png"));
            } catch(InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
        }
    }

private synchronized void enviarDatos(){
    String data="";
    char led1, led2;
        if(btled1.isSelected()){
            led1='1';
            lbled2.setIcon(new ImageIcon("img/led_green2.png"));
        }else{
            led1='0';
            lbled2.setIcon(new ImageIcon("img/led_green1.png"));
        }
        if(btled2.isSelected()){
            led2='1';
            lbled1.setIcon(new ImageIcon("img/led_blue2.png"));
        }else{
            led2='0';
            lbled1.setIcon(new ImageIcon("img/led_blue1.png"));
        }
        data += led1;
        data += led2;
        System.out.println(data+" "+led1+" "+led2);
        con.enviarDatos(data);
   }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btconectar;
    private javax.swing.JButton btdesconectar;
    private javax.swing.JToggleButton btled1;
    private javax.swing.JToggleButton btled2;
    private javax.swing.JComboBox cbPuerto;
    private javax.swing.JLabel iconArduino;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbcasa2;
    private javax.swing.JLabel lbcasaT;
    private javax.swing.JLabel lbinfoCasa;
    private javax.swing.JLabel lbled1;
    private javax.swing.JLabel lbled2;
    private javax.swing.JLabel lbtempIcon;
    private javax.swing.JTextField tfBanoActua;
    private javax.swing.JTextField tfBanoSensores;
    private javax.swing.JTextField tfCocinaAct;
    private javax.swing.JTextField tfCocinaSens;
    private javax.swing.JTextField tfDormitorioActua;
    private javax.swing.JTextField tfDormitorioSensores;
    private javax.swing.JTextField tfSalaAct;
    private javax.swing.JTextField tfSalaSens;
    private javax.swing.JTextField tfTemp;
    private javax.swing.JTextField tfnAct;
    private javax.swing.JTextField tfnSensores;
    // End of variables declaration//GEN-END:variables
}
