    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domogui;

import dispositivos.Actuador;
import dispositivos.Sensor;
import fnArchivo.archivo;
import funciones.Validacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julian
 */
public class frmDispSensor1 extends javax.swing.JFrame {

    /**
     * Creates new form frmDispAct
     */
    public frmDispSensor1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBuscadorS = new javax.swing.JComboBox();
        tfselectorS = new javax.swing.JTextField();
        btConsultarS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSensores = new javax.swing.JTable();
        btIngresarS = new javax.swing.JButton();
        btEditarS = new javax.swing.JButton();
        bteliminarS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dispositivos - Sensores");

        cbBuscadorS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todo", "Id", "Nombre", "Ubicacion", "Modelo", "Fabrica", "Tipo", "Descripcion", "Valor Actual", "Valor Alarma" }));
        cbBuscadorS.setPreferredSize(new java.awt.Dimension(100, 25));

        tfselectorS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfselectorSActionPerformed(evt);
            }
        });

        btConsultarS.setText("Consultar");
        btConsultarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSActionPerformed(evt);
            }
        });

        tbSensores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Ubicacion", "Modelo", "Fabricante", "Tipo", "Descripcion", "Valor Actual", "Valor Alarma"
            }
        ));
        jScrollPane1.setViewportView(tbSensores);

        btIngresarS.setText("Ingresar");
        btIngresarS.setPreferredSize(new java.awt.Dimension(120, 27));
        btIngresarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarSActionPerformed(evt);
            }
        });

        btEditarS.setText("Editar");
        btEditarS.setPreferredSize(new java.awt.Dimension(120, 27));
        btEditarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarSActionPerformed(evt);
            }
        });

        bteliminarS.setText("Eliminar");
        bteliminarS.setPreferredSize(new java.awt.Dimension(120, 27));
        bteliminarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btIngresarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btEditarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(bteliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbBuscadorS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tfselectorS, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btConsultarS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscadorS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfselectorS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultarS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btIngresarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSActionPerformed
        // TODO add your handling code here:
        consultarRegistroS();
    }//GEN-LAST:event_btConsultarSActionPerformed

    private void tfselectorSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfselectorSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfselectorSActionPerformed

    private void btIngresarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarSActionPerformed
        // TODO add your handling code here:
        frmInSensor ingresoS = new frmInSensor();
        ingresoS.setVisible(true);
    }//GEN-LAST:event_btIngresarSActionPerformed

    private void btEditarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarSActionPerformed
        // TODO add your handling code here:
        if(seleccionEdicionValidaS()){
            int fila = tbSensores.getSelectedRow();
            String id = tbSensores.getValueAt(fila,0).toString();
            ArrayList<Sensor> registros = new ArrayList();
            try{
                registros = archivo.obtener_registroS();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al consultar los registros",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);    
            }
            
            if(Validacion.verDupliIdSensor(registros, id)){
                frmEditSensor frm = new frmEditSensor(id,this);
                frm.setVisible(true);                
            }else{
                JOptionPane.showMessageDialog(this,
                    "El registro seleccionado no existe",
                    "Edición",
                    JOptionPane.ERROR_MESSAGE);                    
            }            
        }
    }//GEN-LAST:event_btEditarSActionPerformed

    private void bteliminarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarSActionPerformed
        // TODO add your handling code here:
        if(seleccionEliminacionValidaS()){
            int filas[] =tbSensores.getSelectedRows();
            for (int i = 0; i < filas.length; i++) {
                int fila = filas[i];
                String id = tbSensores.getValueAt(fila,0).toString();
                if(!archivo.eliminar_registroS(id)){
                    JOptionPane.showMessageDialog(this,
                    "Ocurrió un error en la eliminación",
                    "Eliminación",
                    JOptionPane.ERROR_MESSAGE); 
                    return ;
                }                
            }
            
            JOptionPane.showMessageDialog(this,
                    "Se realizó la eliminación correctamente",
                    "Eliminación",
                    JOptionPane.INFORMATION_MESSAGE);        
            consultarRegistroS();
        }
    }//GEN-LAST:event_bteliminarSActionPerformed

    private boolean seleccionEdicionValidaS(){
        int n = tbSensores.getSelectedRowCount();
        if(n!=1){
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un registro para editar",
                    "Edición",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    
    }
    
    private boolean formularioConsultaValidoS(){
        String tipo = cbBuscadorS.getSelectedItem().toString();
        String descripcion = tfselectorS.getText();
        
        if(!tipo.equals("Todo") && descripcion.equals("")){
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripción",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(tipo.equals("Id")){
            try{
                Integer.parseInt(descripcion);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar un número",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        
        if(tipo.equals("Valor Actual")){
            try{
                Integer.parseInt(descripcion);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar un número",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        
        if(tipo.equals("Valor Alarma")){
            try{
                Integer.parseInt(descripcion);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar un número",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        
        if(tipo.equals("Nombre")){
            try{
                descripcion.equals("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripcion",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        if(tipo.equals("Ubicacion")){
            try{
                descripcion.equals("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripcion",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        if(tipo.equals("Modelo")){
            try{
                descripcion.equals("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripcion",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        if(tipo.equals("Fabrica")){
            try{
                descripcion.equals("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripcion",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        if(tipo.equals("Tipo")){
            try{
                descripcion.equals("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripcion",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        if(tipo.equals("Descripcion")){
            try{
                descripcion.equals("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripcion",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }        
        }
        
        return true;
    }
    
    
    public void consultarRegistroS(){
                if(formularioConsultaValidoS()){
            String tipo = cbBuscadorS.getSelectedItem().toString();
            String descripcion = tfselectorS.getText();
            
            try{
                ArrayList<Sensor> registros = archivo.obtener_registroS();
                ArrayList<Sensor> resultado = new ArrayList<Sensor>();
                
                if(tipo.equals("Todo")){
                    resultado = registros;                
                }else{
                    for(Sensor s:registros) {
                        if(tipo.equals("Id")){
                            if(s.getId().contains(descripcion)){
                                resultado.add(s);
                            }                        
                        }else if(tipo.equals("Nombre")){
                            if(s.getNombre().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(s);
                            }                        
                        }else if(tipo.equals("Valor Actual")){
                            if(s.getValAct()==Float.parseFloat(descripcion)){
                                resultado.add(s);
                            }
                        }else if(tipo.equals("Valor Alarma")){
                            if(s.getValAralma()==Float.parseFloat(descripcion)){
                                resultado.add(s);
                            }
                        }else if(tipo.equals("Ubicacion")){
                            if(s.getUbicacion().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(s);
                            }                        
                        }else if(tipo.equals("Modelo")){
                            if(s.getModelo().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(s);
                            }                        
                        }else if(tipo.equals("Fabrica")){
                            if(s.getFabricante().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(s);
                            }                        
                        }else if(tipo.equals("Tipo")){
                            if(s.getTipo().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(s);
                            }                        
                        }else if(tipo.equals("Descripcion")){
                            if(s.getDescripcion().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(s);
                            }                        
                        }                        
                    }                
                }
                
                DefaultTableModel dtm = (DefaultTableModel)tbSensores.getModel();
                dtm.setRowCount(0);
                
                for(Sensor s:resultado){
                    Object[] fila = new Object[9];
                    fila[0] = s.getId();
                    fila[1] = s.getNombre();
                    fila[2] = s.getUbicacion();
                    fila[3] = s.getModelo();
                    fila[4] = s.getFabricante();
                    fila[5] = s.getTipo();
                    fila[6] = s.getDescripcion();
                    fila[7] = s.getValAct();
                    fila[8] = s.getValAralma();
                    dtm.addRow(fila);                
                }
           }catch(Exception e){
                JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al consultar los registros",
                    "Consulta",
                    JOptionPane.ERROR_MESSAGE);
            }            
        }
    }
    
    private boolean seleccionEliminacionValidaS(){ 
        int n = tbSensores.getSelectedRowCount();
        if(n==0){
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar mínimo un registro para eliminar",
                    "Eliminación",
                    JOptionPane.ERROR_MESSAGE);
            return false;        
        }
        int op = JOptionPane.showConfirmDialog(this, "Está seguro de eliminar los registros seleccionados?","Eliminación",JOptionPane.YES_NO_OPTION);
        if(op==0)
            return true;
        else
            return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarS;
    private javax.swing.JButton btEditarS;
    private javax.swing.JButton btIngresarS;
    private javax.swing.JButton bteliminarS;
    private javax.swing.JComboBox cbBuscadorS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSensores;
    private javax.swing.JTextField tfselectorS;
    // End of variables declaration//GEN-END:variables
}
