/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domogui;

import dispositivos.Actuador;
import fnArchivo.archivo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmEditActuador extends javax.swing.JFrame {
    frmDispAct editA;
    /**
     * Creates new form frmInActuador
     * @param id
     * @param editS
     */
    public frmEditActuador(String id, frmDispAct editA) {
        initComponents();
        this.editA = editA;
        try{
            ArrayList<Actuador> registros = archivo.obtener_registroA();
            for(Actuador a:registros){
                if(a.getaId().equals(id)){
                    tfAct_id.setText(id);
                    tfAnombre.setText(a.getaNombre());
                    tfAmodel.setText(a.getaModelo());
                    //String ubic     = cbUbi.getSelectedItem().toString();
                    tfAfab.setText(a.getaFabricante());
                    tfAtipo.setText(a.getaTipo());
                    tfAdes.setText(a.getaDecripcion());
                    tfAestado.setText(Integer.toString(a.getaEstado()));
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
            "Ocurrió un error al consultar los datos del registro",
            "Edición",
            JOptionPane.ERROR_MESSAGE);
        } 
        
        
        //configurando imagen en etiqueta
        try{
            BufferedImage acticon = ImageIO.read(new File("imgsp/act_icon.png"));
            lbact_icon.setIcon(new ImageIcon(acticon));
        }catch (Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAct_id = new javax.swing.JLabel();
        lbAct_nomb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAct_id = new javax.swing.JTextField();
        tfAnombre = new javax.swing.JTextField();
        tfAmodel = new javax.swing.JTextField();
        tfAfab = new javax.swing.JTextField();
        tfAtipo = new javax.swing.JTextField();
        tfAdes = new javax.swing.JTextField();
        lbact_icon = new javax.swing.JLabel();
        btEditAct = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        cbUbi = new javax.swing.JComboBox();
        tfAestado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edición de Actuadores");

        lbAct_id.setText("Id:");

        lbAct_nomb.setText("Nombre:");

        jLabel2.setText("Ubicación:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Fabricante:");

        jLabel5.setText("Tipo:");

        jLabel6.setText("Descripción:");

        jLabel7.setText("Estado:");

        tfAct_id.setEditable(false);
        tfAct_id.setPreferredSize(new java.awt.Dimension(120, 25));
        tfAct_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAct_idActionPerformed(evt);
            }
        });

        tfAnombre.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAmodel.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAfab.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAtipo.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAdes.setPreferredSize(new java.awt.Dimension(120, 25));
        tfAdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdesActionPerformed(evt);
            }
        });

        btEditAct.setText("Editar");
        btEditAct.setPreferredSize(new java.awt.Dimension(75, 30));
        btEditAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.setPreferredSize(new java.awt.Dimension(75, 30));
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        cbUbi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dormitorio", "Sala", "Baño", "Cocina/Comedor" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btEditAct, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbact_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAct_nomb)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lbAct_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAfab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAct_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(cbUbi, 0, 131, Short.MAX_VALUE)
                            .addComponent(tfAmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAestado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAct_id)
                            .addComponent(tfAct_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAct_nomb)
                            .addComponent(tfAnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfAmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfAfab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbact_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfAestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEditAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tfAdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAdesActionPerformed

    private void tfAct_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAct_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAct_idActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btEditActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActActionPerformed
        // TODO add your handling code here:
        if(formularioValido()){
            String id = tfAct_id.getText();
            String nombre   = tfAnombre.getText();
            String ubic     = cbUbi.getSelectedItem().toString();
            String model    = tfAmodel.getText();
            String fabrica  = tfAfab.getText();
            String tipo     = tfAtipo.getText();
            String descripcion = tfAdes.getText();
            int estado         = Integer.parseInt(tfAestado.getText());
            Actuador a = new Actuador(id, nombre, ubic, model, fabrica, tipo, descripcion, estado);
            if(archivo.editar_registroA(a)){
                JOptionPane.showMessageDialog(this,"Se editó correctamente el Actuador", "Edición",JOptionPane.INFORMATION_MESSAGE);            
                this.editA.consultarRegistroA();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Ocurrió un error en la edición", "Error",JOptionPane.ERROR_MESSAGE);            
            }
        }              
    }//GEN-LAST:event_btEditActActionPerformed

private boolean formularioValido(){
        if(tfAct_id.getText().equals("") ||
           tfAnombre.getText().equals("") ||
           tfAnombre.getText().equals("") ||
           tfAfab.getText().equals("") ||
            tfAtipo.getText().equals("") ||
            tfAdes.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Formulario incompleto","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try{
            Integer.parseInt(tfAct_id.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El Id debe ser un número","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
private void limpiarFormulario(){
        tfAnombre.setText("");
        tfAmodel.setText("");
        tfAfab.setText("");
        tfAtipo.setText("");
        tfAdes.setText("");
        tfAestado.setText("");
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditAct;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox cbUbi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbAct_id;
    private javax.swing.JLabel lbAct_nomb;
    private javax.swing.JLabel lbact_icon;
    private javax.swing.JTextField tfAct_id;
    private javax.swing.JTextField tfAdes;
    private javax.swing.JTextField tfAestado;
    private javax.swing.JTextField tfAfab;
    private javax.swing.JTextField tfAmodel;
    private javax.swing.JTextField tfAnombre;
    private javax.swing.JTextField tfAtipo;
    // End of variables declaration//GEN-END:variables
}
