/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domogui;

import funciones.Validacion;
import dispositivos.Actuador;
import fnArchivo.archivo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmInActuador extends javax.swing.JFrame {

    /**
     * Creates new form frmInActuador
     */
    public frmInActuador() {
        initComponents();
        
        //configurando imagen en etiqueta
        try{
            BufferedImage acticon = ImageIO.read(new File("imgsp/act_icon.png"));
            act_icon.setIcon(new ImageIcon(acticon));
        }catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAct_id = new javax.swing.JLabel();
        lbAct_nomb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAct_id = new javax.swing.JTextField();
        tfAnom = new javax.swing.JTextField();
        tfaModel = new javax.swing.JTextField();
        tfAfab = new javax.swing.JTextField();
        tfAtipo = new javax.swing.JTextField();
        tfAdes = new javax.swing.JTextField();
        act_icon = new javax.swing.JLabel();
        btIngresarAct = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        cbUbi = new javax.swing.JComboBox();
        tfAestado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de Actuadores");

        lbAct_id.setText("Id:");

        lbAct_nomb.setText("Nombre:");

        jLabel2.setText("Ubicación:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Fabricante:");

        jLabel5.setText("Tipo:");

        jLabel6.setText("Descripción:");

        jLabel7.setText("Estado:");

        tfAct_id.setEditable(false);
        tfAct_id.setPreferredSize(new java.awt.Dimension(120, 25));
        tfAct_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAct_idActionPerformed(evt);
            }
        });

        tfAnom.setPreferredSize(new java.awt.Dimension(120, 25));

        tfaModel.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAfab.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAtipo.setPreferredSize(new java.awt.Dimension(120, 25));

        tfAdes.setPreferredSize(new java.awt.Dimension(120, 25));
        tfAdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdesActionPerformed(evt);
            }
        });

        btIngresarAct.setText("Ingresar");
        btIngresarAct.setPreferredSize(new java.awt.Dimension(75, 30));
        btIngresarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.setPreferredSize(new java.awt.Dimension(75, 30));
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        cbUbi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dormitorio", "Sala", "Baño", "Cocina/Comedor" }));

        tfAestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btIngresarAct, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(act_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAct_nomb)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lbAct_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAfab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAct_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAnom, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(cbUbi, 0, 131, Short.MAX_VALUE)
                            .addComponent(tfaModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAestado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAct_id)
                            .addComponent(tfAct_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAct_nomb)
                            .addComponent(tfAnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfaModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfAfab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(act_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfAestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btIngresarAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean formularioValido(){
        if(tfAct_id.getText().equals("") ||
           tfAnom.getText().equals("") ||
           tfaModel.getText().equals("") ||
           tfAfab.getText().equals("") ||
            tfAtipo.getText().equals("") ||
            tfAdes.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Formulario incompleto","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try{
            Integer.parseInt(tfAct_id.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "El Id debe ser un número","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try{
            ArrayList<Actuador> registros = archivo.obtener_registroA();
            if(Validacion.verDupliIdAct(registros,tfAct_id.getText())){
                JOptionPane.showMessageDialog(this, "El id se encuentra registrado","Validación",JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }catch(Exception e){
            return false;
        }
        
        return true;
    }
    
    private void limpiarFormulario(){
        //tfAct_id.setText("");
        tfAnom.setText("");
        tfaModel.setText("");
        tfAfab.setText("");
        tfAtipo.setText("");
        tfAdes.setText("");
        tfAestado.setText("");
    }
    
    private void tfAdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAdesActionPerformed

    private void tfAct_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAct_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAct_idActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void tfAestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAestadoActionPerformed

    private void btIngresarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActActionPerformed
        /*
        try {
            // TODO add your handling code here:
            ArrayList<Actuador> ract = archivo.obtener_registroA();
            tfAct_id.setText(IdActual(ract));
        } catch (Exception ex) {
            Logger.getLogger(frmInActuador.class.getName()).log(Level.SEVERE, null, ex);
        }
       // tfAct_id.setText(IdActual(ract));
        */
        
        if(formularioValido()){
            String id       = tfAct_id.getText();
            String nombre   = tfAnom.getText();
            String ubic     = cbUbi.getSelectedItem().toString();
            String model    = tfaModel.getText();
            String fabrica  = tfAfab.getText();
            String tipo     = tfAtipo.getText();
            String descripcion = tfAdes.getText();
            int estado   = Integer.parseInt(tfAestado.getText());            
            
            Actuador a = new Actuador(id, nombre, ubic, model, fabrica, tipo, descripcion, estado);
            if(archivo.insert_registroA(a)){
                JOptionPane.showMessageDialog(this,"Se ingresó correctamente el Actuador", "Ingreso",JOptionPane.INFORMATION_MESSAGE);            
                limpiarFormulario();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Ocurrió un error en el ingreso", "Error",JOptionPane.ERROR_MESSAGE);            
            }
        }
    }//GEN-LAST:event_btIngresarActActionPerformed

    /*
    private String IdActual(ArrayList<Actuador> ract){
       // ArrayList<Actuador> ract = archivo.obtener_registroA();
        int idActual=1;
        if (ract==null){
            idActual = Integer.parseInt(ract.get(ract.size()-1).getaId());
        }
        return String.valueOf(idActual);
    }
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel act_icon;
    private javax.swing.JButton btIngresarAct;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox cbUbi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbAct_id;
    private javax.swing.JLabel lbAct_nomb;
    private javax.swing.JTextField tfAct_id;
    private javax.swing.JTextField tfAdes;
    private javax.swing.JTextField tfAestado;
    private javax.swing.JTextField tfAfab;
    private javax.swing.JTextField tfAnom;
    private javax.swing.JTextField tfAtipo;
    private javax.swing.JTextField tfaModel;
    // End of variables declaration//GEN-END:variables
}
